/* @bruin
name: mart.product_performance
type: duckdb.sql
depends:
  - staging.stg_retail

materialization:
  type: table

description: "Product-level performance analysis for the UK Online Retail dataset. Ranks products by revenue, quantity sold, number of orders, and return rate. Useful for identifying best sellers, worst performers, and products with high return rates."

columns:
  - name: stock_code
    description: "Unique product code."
    checks:
      - name: not_null
      - name: unique
  - name: description
    description: "Product name."
  - name: total_revenue
    description: "Total gross revenue generated by the product in GBP."
    checks:
      - name: not_null
  - name: total_quantity_sold
    description: "Total units sold, excluding cancellations."
    checks:
      - name: not_null
  - name: total_orders
    description: "Number of distinct invoices containing this product."
    checks:
      - name: not_null
  - name: total_customers
    description: "Number of distinct customers who purchased this product."
    checks:
      - name: not_null
  - name: avg_unit_price
    description: "Average unit price of the product in GBP."
    checks:
      - name: not_null
  - name: return_quantity
    description: "Total units returned or cancelled for this product."
    checks:
      - name: not_null
  - name: return_rate_pct
    description: "Returns as a percentage of total units sold."
    checks:
      - name: not_null
  - name: revenue_rank
    description: "Rank of the product by total revenue, 1 being highest."
    checks:
      - name: not_null
@bruin */

WITH sales AS (
    SELECT
        stock_code,
        -- Use the most common description for each stock code
        MODE(description)                        AS description,
        ROUND(SUM(revenue), 2)                   AS total_revenue,
        SUM(quantity)                            AS total_quantity_sold,
        COUNT(DISTINCT invoice)                  AS total_orders,
        COUNT(DISTINCT customer_id)              AS total_customers,
        ROUND(AVG(price), 2)                     AS avg_unit_price
    FROM staging.stg_retail
    WHERE is_cancellation = FALSE
      AND quantity > 0
    GROUP BY stock_code
),

returns AS (
    SELECT
        stock_code,
        ABS(SUM(quantity))                       AS return_quantity
    FROM staging.stg_retail
    WHERE is_cancellation = TRUE
    GROUP BY stock_code
)

SELECT
    s.stock_code,
    s.description,
    s.total_revenue,
    s.total_quantity_sold,
    s.total_orders,
    s.total_customers,
    s.avg_unit_price,
    COALESCE(r.return_quantity, 0)               AS return_quantity,
    ROUND(
        COALESCE(r.return_quantity, 0) * 100.0
        / NULLIF(s.total_quantity_sold, 0),
    2)                                           AS return_rate_pct,
    RANK() OVER (ORDER BY s.total_revenue DESC)  AS revenue_rank
FROM sales s
LEFT JOIN returns r
    ON s.stock_code = r.stock_code
ORDER BY s.total_revenue DESC