/* @bruin

name: mart.customer_rfm
type: duckdb.sql
description: RFM (Recency, Frequency, Monetary) customer segmentation for the UK Online Retail dataset. Each customer is scored 1-4 on recency, frequency and monetary value, then assigned a business segment such as Champion, Loyal, At Risk or Lost. Enables targeted retention and marketing strategies.

materialization:
  type: table

depends:
  - staging.stg_retail

columns:
  - name: customer_id
    type: BIGINT
    description: Unique customer identifier.
    checks:
      - name: not_null
      - name: unique
  - name: country
    type: VARCHAR
    description: Country where the customer is based.
    checks:
      - name: not_null
  - name: last_purchase_date
    type: DATE
    description: Date of the customer's most recent purchase.
    checks:
      - name: not_null
  - name: recency_days
    type: BIGINT
    description: Number of days since the customer's last purchase, relative to the last date in the dataset.
    checks:
      - name: not_null
  - name: frequency
    type: BIGINT
    description: Total number of distinct orders placed by the customer.
    checks:
      - name: not_null
  - name: monetary
    type: DOUBLE
    description: Total revenue generated by the customer in GBP.
    checks:
      - name: not_null
  - name: r_score
    type: BIGINT
    description: Recency score from 1 (least recent) to 4 (most recent).
    checks:
      - name: not_null
  - name: f_score
    type: BIGINT
    description: Frequency score from 1 (least frequent) to 4 (most frequent).
    checks:
      - name: not_null
  - name: m_score
    type: BIGINT
    description: Monetary score from 1 (lowest spend) to 4 (highest spend).
    checks:
      - name: not_null
  - name: rfm_score
    type: VARCHAR
    description: Combined RFM score as a string (e.g. 444 = best customer).
    checks:
      - name: not_null
  - name: customer_segment
    type: VARCHAR
    description: 'Business segment label derived from RFM scores: Champion, Loyal, Potential Loyalist, At Risk, Lost, or Others.'
    checks:
      - name: not_null

@bruin */

WITH reference_date AS (
    -- Use the last transaction date in the dataset as the reference point
    SELECT MAX(invoice_date::DATE) AS max_date
    FROM staging.stg_retail
    WHERE is_cancellation = FALSE
),

customer_metrics AS (
    SELECT
        customer_id,
        MAX(country)                                     AS country,
        MAX(invoice_date::DATE)                          AS last_purchase_date,
        DATE_DIFF('day',
            MAX(invoice_date::DATE),
            (SELECT max_date FROM reference_date))       AS recency_days,
        COUNT(DISTINCT invoice)                          AS frequency,
        ROUND(SUM(revenue), 2)                           AS monetary
    FROM staging.stg_retail
    WHERE is_cancellation = FALSE
      AND quantity > 0
      AND customer_id IS NOT NULL
    GROUP BY customer_id
),

rfm_scores AS (
    SELECT
        *,
        NTILE(4) OVER (ORDER BY recency_days DESC)      AS r_score,
        NTILE(4) OVER (ORDER BY frequency ASC)          AS f_score,
        NTILE(4) OVER (ORDER BY monetary ASC)           AS m_score
    FROM customer_metrics
)

SELECT
    customer_id,
    country,
    last_purchase_date,
    recency_days,
    frequency,
    monetary,
    r_score,
    f_score,
    m_score,
    CONCAT(r_score, f_score, m_score)                   AS rfm_score,
    CASE
        WHEN r_score = 4 AND f_score = 4 AND m_score = 4
            THEN 'Champion'
        WHEN r_score >= 3 AND f_score >= 3
            THEN 'Loyal'
        WHEN r_score >= 3 AND f_score <= 2
            THEN 'Potential Loyalist'
        WHEN r_score <= 2 AND f_score >= 3
            THEN 'At Risk'
        WHEN r_score = 1 AND f_score = 1
            THEN 'Lost'
        ELSE 'Others'
    END                                                  AS customer_segment
FROM rfm_scores
ORDER BY monetary DESC
